
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkiyjabymmdhyjlqspio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpraXlqYWJ5bW1kaHlqbHFzcGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODA1NTQsImV4cCI6MjA2MjQ1NjU1NH0.1rPbXj8HqjshLywITGMM-6Rof4PdQ6OdBQp8PB08tPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'quiz-app-storage-key'
    }
  }
);
